### ISSUE TITLE
Add RingCentral auth connector

### ISSUE THREAD

**Issue by RajatPawar** [amp-labs/connectors#183]

**Comment by Listener430** [comment]
Keeping the ticket in on-hold status due to the issue with accesing the sandbox (dev portal access works fine, but trying to access the RingCentral account triggers access denied error. Can't get a token without this.

**Comment by Listener430** [comment]
Thanks to Willie's support, the issues with sandbox access were resolved, here is the link to the documentation - [https://ampersand.slab.com/posts/ring-central-documentation-43xi0z2f](url)

**Comment by Listener430** [comment]
Moving to Blocked status pending the issue resolution on access to prod.

**Comment by Listener430** [comment]
Removed substitutions to support test env, now the connector is strictly for the prod version
